config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'
  root 'hello#index'
  resources :users, only: [:show]
  resources :tweets do 
    
    resource :bookmark, only: %i[create destroy]
    collection do
      get 'bookmarks'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tweets, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_tweets, through: :bookmarks, source: :tweet
  def self.model_name 
    ActiveModel::Name.new(self, nil, "Tweet") 
  end
  
  def own?(object)
    id == object.user_id
  end

  def bookmark?(tweet)
    bookmarks.exists?(tweet_id: tweet.id)
  end

  def bookmark(tweet)
    bookmarks.create(user_id: id, tweet_id: tweet.id) unless bookmark?(tweet)
  end  

  def unbookmark(tweet)
    bookmarks.find_by(tweet_id: tweet.id)&.destroy
  end
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :tweets, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_tweets, through: :bookmarks, source: :tweet

  def own?(object)
    id == object.user_id
  end

  def bookmark?(tweet)
    bookmarks.exists?(tweet_id: tweet.id)
  end

  def bookmark(tweet)
    bookmarks.create(user_id: id, tweet_id: tweet.id) unless bookmark?(tweet)
  end  

  def unbookmark(tweet)
    bookmarks.find_by(tweet_id: tweet.id)&.destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!
  
    def create
      @tweet = Tweet.find(params[:tweet_id])
      current_user.bookmark(@tweet)
      respond_to do |format|
        format.js   # create.js.erb をレンダリング
        format.html { redirect_to request.referer, notice: "ブックマークしました" }
      end
    end
  
    def destroy
      @tweet = Tweet.find(params[:tweet_id])
      current_user.unbookmark(@tweet)
      respond_to do |format|
        format.js   # destroy.js.erb をレンダリング
        format.html { redirect_to request.referer, notice: "ブックマークを解除しました" }
      end
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
  def link
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  
    def index
      @tweets = Tweet.all
    
      # キーワード検索
      if params[:search].present?
        @tweets = @tweets.where("body LIKE ?", "%#{params[:search]}%")
      end
    
      # タグ検索 (OR検索)
      @tweets = params[:tag_id].present? ? Tag.find(params[:tag_id]).tweets : Tweet.all

    
      @tweets = @tweets.page(params[:page]).per(3)
    end
    
  
  def new
    @tweet = Tweet.new
  end
  def create
    puts "デバッグ: params = #{params.inspect}"
    tweet = Tweet.new(tweet_params)
    puts "デバッグ: tweet_params = #{@tweet.inspect}"
    tweet.user_id = current_user.id
    if tweet.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end
  def show
    @tweet = Tweet.find(params[:id])
    
  end
  def edit
    @tweet = Tweet.find(params[:id])
  end
  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  def bookmarks
    @tweets = current_user.bookmark_tweets
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body, :title, :name, :username, :overall, tag_ids: [],)
  end
  def tweet_params
    params.require(:tweet).permit(:body, :title, tag_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def safe_user_path(user)
    return "#" if user.nil? || user.id.nil?
    user_path(user.id)
  rescue StandardError
    "#"
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def get_percent(number) 
    if number.present?
      cal_percent = number/5.to_f * 100
      # calPercent = number/10.to_f * 100
      #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
      percent = cal_percent.round
      #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
      return percent.to_s
    else
      return 0
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_bookmark.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>
<div class="right-container">
<%= link_to tweet_bookmark_path(tweet),
            method: :post,
            remote: true,
            data: { turbo: "false" },
            id: "js-bookmark-button-for-tweet-#{tweet.id}" do %>
            
    <i class="fa-regular fa-bookmark"></i>
</div>
<% end %>

app/views/bookmarks/_unbookmark.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>
<div class="right-container">
<%= link_to tweet_bookmark_path(tweet),
            method: :delete,
            remote: true,
            data: { turbo: "false" },
            id: "js-bookmark-button-for-tweet-#{tweet.id}" do %>

    <i class="fa-solid fa-bookmark"></i>
</div>
<% end %>

app/views/bookmarks/create.js.erb
document.getElementById("js-bookmark-button-for-tweet-<%= @tweet.id %>").innerHTML = "<%= j(render 'bookmarks/unbookmark', tweet: @tweet) %>";

app/views/bookmarks/destroy.js.erb
document.getElementById("js-bookmark-button-for-tweet-<%= @tweet.id %>").innerHTML = "<%= j(render 'bookmarks/bookmark', tweet: @tweet) %>";

app/views/hello/index.html.erb
<%= stylesheet_link_tag 'hello', :media => "all" %>

<body>
    <div class="container">
        <%= link_to "ログイン", tweets_path, class: "btn btn-login" %>
        <%= link_to "新規登録", new_user_registration_path, class: "btn btn-signup" %>
    </div>
</body>

app/views/hello/link.html.erb
<%= link_to 'トップページ', hello_index_path %>
<%= link_to '一覧表示', tweets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <section id="second-block">
    <head>
      <title>Screenspot</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/3e8b362a6f.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1>ScreenSpot</h1>
      <div class="header-list">
      <ul>
        <li><%= link_to tweets_path do %>
          <i class="fa fa-home"></i>
        <% end %></li>
        <li><%= link_to new_tweet_path do %>
          <i class="fa-solid fa-pen"></i>
        <% end %></li>
        <li><%= link_to destroy_user_session_path, method: :delete, class: "logout-link" do %>
          <i class="fas fa-sign-out-alt"></i>
        <% end %></li>
      </ul>
      </div>
    </header>
    <main>
    <%= yield %>
    </main>
    <footer>
      <p>Copyright © GeekSalon All Rights Reserved.</p>
  </body>
  </html>
  </section>

app/views/tweets/_tweet.html.erb
<%= stylesheet_link_tag 'index', media: "all" %>
<div class="tweet">
    <% if user_signed_in? %>
        <% if local_assigns[:show_title] %>
            <p><%= tweet.title %></p>
        <% end %>

        <% unless local_assigns[:bookmark_only] %>
            <% if tweet.tags.present? %>
                <div class="tags">
                    <% tweet.tags.each do |tag| %>
                        <span class="tag"><%= tag.name %></span>
                    <% end %>
                </div> 
            <% end %>
        <% end %>

        <% if local_assigns[:bookmark_only] %>
            <div class="bookmark-icon">
                <% if current_user.bookmark?(tweet) %>
                    <%= render 'bookmarks/unbookmark', tweet: tweet %>
                <% else %>
                    <%= render 'bookmarks/bookmark', tweet: tweet %>
                <% end %>
            </div>
        <% end %>
    <% end %>
</div>

app/views/tweets/bookmarks.html.erb
<h1>ブックマークしたツイート一覧</h1>

<% if @tweets.present? %>
    <% @tweets.each do |tweet| %>
    <%= render 'tweet', tweet: tweet %>
    <% end %>
<% else %>
    <p>まだブックマークしたツイートはありません。</p>
<% end %>

app/views/tweets/edit.html.erb
<div class='container'>
  <p class="title">投稿を編集する</p>
  <%= form_for @tweet do |f| %>

  <div class="field">
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, class: "input-field" %>
    </div>

  <div class="field">
    <%= f.label :overall, "総合評価", class: "label-title" %>
  </div>
  <div class="post_form">
    <%= f.radio_button :overall, 5 ,id: 'star1'%>
    <label for="star1"><span class="text">最高</span>★</label>

    <%= f.radio_button :overall, 4 ,id: 'star2'%>
    <label for="star2"><span class="text">良い</span>★</label>

    <%= f.radio_button :overall, 3 ,id: 'star3'%>
    <label for="star3"><span class="text">普通</span>★</label>

    <%= f.radio_button :overall, 2 ,id: 'star4'%>
    <label for="star4"><span class="text">悪い</span>★</label>

    <%= f.radio_button :overall, 1 ,id: 'star5'%>
    <label for="star5"><span class="text">最悪</span>★</label>
  </div>

  <div class='form-group'>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
          <div class='form-check'>
              <%= tag.label class: 'form-check-label' do %>
                  <%= tag.check_box class: 'form-check-input' %>
                  <%= tag.text %>
              <% end %>
          </div>
      <% end %>
    </div>

    <div class="field">
      <%= f.label :title, "テキストを追加" %>
      <%= f.text_area :body, class: "textarea-field" %>
    </div>

    <%= f.submit "編集する", class: "btn-submit" %>
  <% end %>
</div>

app/views/tweets/index.html.erb
<%= stylesheet_link_tag 'index', media: "all" %>

  <% if user_signed_in? %>
    <%= link_to user_path(current_user) do %>
      <i class="fa-solid fa-circle-user"></i>
    <% end %>
  <% end %>
    
<div class="search-box">
  <%= form_with url: tweets_path, method: :get, local: true do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag '検索' %>
  <% end %>
</div>

<div class="pagination-container">
  <%= page_entries_info @tweets %>
  <div class="pagination-links">
    <%= paginate @tweets, params: { search: params[:search], tag_ids: params[:tag_ids] } %>
  </div>
</div>

<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">
      <div class="main-box">
        <div class="title-actions-container">
          <%= render 'tweet', tweet: t, bookmark_only: true %>
          <div class="title">
            <%= t.title %>
          </div>
          <div class="left-container">
            <h3>総合評価：
              <span class="star-rating">
                <span class="star-rating-front" style="width: <%= get_percent(t.overall) %>%; overflow: hidden;">★★★★★</span>
                <span class="star-rating-back">★★★★★</span>
              </span>
            </h3>
            <%= render 'tweet', tweet: t %>
            <%= t.body %>
            <p>投稿者: <%= t.user&.name || "名無しユーザー" %></p>
            <p>Email: <%= t.user&.email || "メール情報なし" %></p>
            
            <%= link_to "詳細", tweet_path(t), class: "btn-detail" %>
            <% if user_signed_in? && current_user.id == t.user_id %>
              <%= link_to edit_tweet_path(t), class: "btn-edit" do %>
                <i class="fa-solid fa-pen-to-square"></i>
              <% end %>
              <%= link_to tweet_path(t), method: :delete, class: "btn-delete" do %>
                <i class="fa-solid fa-trash"></i>
              <% end %>
            <% end %>
            <p class="time"><%= t.created_at %></p>
          </div>
        </div> 
      </div>
    </div>
  <% end %>
</div>

<div class="tag-container">
  <h3>ジャンル検索</h3>
  <%= form_tag tweets_path, method: :get, class: 'boards__searchForm' do %>
  
      <%= select_tag :tag_id,
        options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
        {
        prompt: 'タグで絞り込み検索',
        onchange: 'submit(this.form);'
        }
      %>
  <% end %>    
</div>

app/views/tweets/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>
<div class='container'>
  <p class="title">新規投稿</p>

  <%= form_for @tweet, url: tweets_path, method: :post do |f| %>
    <div class="field">
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, class: "input-field" %>
    </div>



  
  <div class="field">
  <%= f.label :overall, "総合評価", class: "label-title" %>
  </div>
  <div class="post_form">
    <%= f.radio_button :overall, 5 ,id: 'star1'%>
    <label for="star1"><span class="text">最高</span>★</label>

    <%= f.radio_button :overall, 4 ,id: 'star2'%>
    <label for="star2"><span class="text">良い</span>★</label>

    <%= f.radio_button :overall, 3 ,id: 'star3'%>
    <label for="star3"><span class="text">普通</span>★</label>

    <%= f.radio_button :overall, 2 ,id: 'star4'%>
    <label for="star4"><span class="text">悪い</span>★</label>

    <%= f.radio_button :overall, 1 ,id: 'star5'%>
    <label for="star5"><span class="text">最悪</span>★</label>
  </div>

  <div class='form-group'>
      <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
    <div>
      <%= tag.label do %>
        <%= tag.check_box %>
        <%= tag.text %>
      <% end %>
    </div>
        <% end %>
    </div>

  <div class="field">
    <%= f.label :title, "テキストを追加" %>
    <%= f.text_area :body, class: "textarea-field" %>
  </div>
    
      <%= f.submit "POST", class: "btn-submit" %>
  <% end %>
  <%= link_to "投稿一覧に戻る", tweets_path %>
</div>

app/views/tweets/show.html.erb
<h3>投稿詳細</h3>
<div class="tweet">
  <p><%= @tweet.title %></p>
  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at %></p>
</div>
<% @tweet.tags.each do |tag| %>
    <%= tag.name %>
<% end %>

<%= link_to "投稿一覧に戻る", tweets_path %>
<% if user_signed_in? && current_user.id == @tweet.user_id %>
  <%= link_to "編集する", edit_tweet_path(@tweet.id) %>
<% end %> 

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'users', media: "all" %>
<body>
  <main>
    <h2><i class="fa-solid fa-circle-user"></i>&nbsp;マイページ</h2>
    <section class="user-info">
      <h3>ユーザー情報</h3>
      <div class="user-details">
        <p>名前 : <%= @user.name %></p>
        <p>メールアドレス : <%= @user.email %></p>
        <p>プロフィール : <%= @user.profile %></p>
      </div>
      <div class="edit-link">
        <%= link_to edit_user_registration_path, class: "edit-btn" do %>
          <i class="fas fa-edit"></i> 編集する
        <% end %>
      </div>
    </section>

<% if current_user.id == @user.id %>
<% end %>

    <section class="bookmarks">
      <h3>ブックマークした作品</h3>
      <% if @user.bookmark_tweets.any? %>
        <% @user.bookmark_tweets.each do |tweet| %>
          <%= render 'tweets/tweet', tweet: tweet, show_title: true %>
        <% end %>
      <% else %>
        <p>まだブックマークしたツイートはありません。</p>
      <% end %>
    </section>

    <section class="posts">
      <h3>過去の投稿</h3>
      <div class="postbox">
        <% @user.tweets.each do |t| %>
          <div class="postbox-item">
            <p class="post-title"><%= t.title %></p>
          </div>
        <% end %>
      </div>
    </section>

    <%= link_to "投稿一覧に戻る", tweets_path, class: "back-link" %>

  </main>
</body>